### ISSUE TITLE
Missing "." in relative folder path, S3 files not loading

### ISSUE THREAD

**Issue by ujnm** [aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools#1]
The code is not opening the files from s3 as the path is" open(f'./{local_ui_template_directory_name}/index.html', encoding='utf-8')" and should have two dots, so "open(f'../{local_ui_template_directory_name}/index.html', encoding='utf-8')" in 351st line in comprehend-ssie-annotation-tool-cli.py

**Comment by dnlen** [comment]
Hi ujnm, there are two parts to resolve this.
1. Please leave the path as was originally with a single dot: f'./{local_ui_template_directory_name}/index.html'.
2. When the script is run in the terminal, please make sure you are in the root directory of the package (one directory up from the bin/ directory)
Relative pathing is used in the script to locate and upload local package data, so it's important the script is run from the package root directory.

**Comment by ujnm** [comment]
This solution worked, thank you!
