### ISSUE TITLE
utils.s3_helper not found

### ISSUE THREAD

**Issue by hs-afactory** [aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools#10]
Hi Team,
I am getting error "ModuleNotFoundError: No module named 'utils.s3_helper'"
While running "comprehend-ssie-annotation-tool-cli.py"
I am not able to find dependency.
I want to annotate pdf to classify type of pdf. Recured manifest file to be generate for ML model testing.

**Comment by jetsonai11** [comment]
Hi @dnlen , thank you for this project. I am running into the same issue and am getting error "ModuleNotFoundError: No module named 'utils.s3_helper'". I have just installed this annotation tool yesterday, so it should have been installed based on the latest commit. How should I fix this?

**Comment by dnlen** [comment]
@jetsonai11 @hs-afactory Before running the command to create a labeling job, please ensure that you are in the shell by following "Step 3 Prerequisites" from the README.

**Comment by jetsonai11** [comment]
@dnlen Great, that worked, thank you!
