### ISSUE TITLE
Zoom feature

### ISSUE THREAD

**Issue by HighPoint** [aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools#11]
How can I add a zoom feature to the annotation tool? Zoom is possible in the pdf.js backbone.

**Comment by dnlen** [comment]
Unfortunately, this is not something that can be done from this Github repository as it requires change in the ui-template directory. We do have this zoom feature as a task in our backlog as it has also been requested by others.

**Comment by HighPoint** [comment]
Thank you for your quick response! The ui-template directory is part of this GitHub. Is there a master ui-template GitHub used for most AWS PDF projects?

**Comment by dnlen** [comment]
The ui-template directory contains built artifacts from an internal package which is not public.

**Comment by HighPoint** [comment]
Thank you for the info!
