### ISSUE TITLE
Documents Appear to be "Read Only"

### ISSUE THREAD

**Issue by jetsonai11** [aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools#13]
Hi developers! I was able to create a labeling job and open the annotation tool to perform labeling. However, I could only annotate on one page of each document, while all the other pages of the same document is "read only". All of the entities would not necessarily appear on the same page, so I would like to have the ability to annotate every page of the same document. How can I fix that? Thanks!

<img width="899" alt="Screen Shot 2022-07-12 at 9 27 45 AM" src="https://user-images.githubusercontent.com/64779050/178502514-82f016e7-6df0-4c2a-92a6-664426dae629.png">

**Comment by jetsonai11** [comment]
Can someone please take a look and help? This is really urgent and I have been having troubles with the annotation tool... would really appreciate some assistance. :(

**Comment by dnlen** [comment]
The Read-Only page navigation is mainly used to for page context. Each labeling job task is a single page. When that page is complete, clicking Submit will load another page. All the pages will eventually be loaded one-by-one to annotate.

Note: Sagemaker GroundTruth may not load pages in sequential order.

**Comment by jetsonai11** [comment]
Thanks for your response @dnlen !
However, there is a more serious issue with the annotation tool - it is not able to let me select certain texts within a document. For instance, for this file, when I was selecting the text segment "Total Usage 95 kWh", I was only able to select "Total Usage" but not "95 kWh". For my particular task, the "95 kWh" is where the important information is, but the tool fails to allow to label it. Is there a fix for this?


<img width="142" alt="Screen Shot 2022-07-12 at 6 31 54 PM" src="https://user-images.githubusercontent.com/64779050/178609005-4f0d6bec-0ef4-43f4-87ba-98ca6e467bcb.png">

<img width="461" alt="Screen Shot 2022-07-12 at 6 30 00 PM" src="https://user-images.githubusercontent.com/64779050/178609009-35bc867b-b121-4b36-a94d-552e7dc38cc8.png">

**Comment by dnlen** [comment]
For your issue, by default, some text on PDF pages may be detected as part of an image which is not parsed. One thing you can do to parse as much text as possible is to use the `--use-textract-only` option when creating the labeling job which will flag us to use Textract's DetectDocumentText API to parse the PDFs.

Note that this could increase cost as Textract API calls are being made.

**Comment by jetsonai11** [comment]
@dnlen Got it, thank you!
