### ISSUE TITLE
Is there a way to edit or remove annotated pdf files after completing the labeling task?

### ISSUE THREAD

**Issue by jetsonai11** [aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools#14]
Hi! I have just finished labeling my pdf files, but I have found a few documents which were missing the entities I wanted to label; therefore, I want to exclude those documents before I start a model training task. Is there a way to do so? Can I just delete the json files that are in this directory: `<labeling job id>/annotations/consolidated-annotation/consolidation-response/iteration-1/annotations `?

Also, is the labeled dataset in a usable format for training entity extraction models on other platforms, such as spaCy?

**Comment by dnlen** [comment]
For the document pages that you want to exclude from `<labeling job id>/annotations/consolidated-annotation/consolidation-response/iteration-1/annotations`, you would want to open the <labeling job id>/manifests/output.manifest file and remove the lines with a reference to those specific annotation files.

**Comment by jetsonai11** [comment]
Thanks @dnlen for the response, I have a couple more questions to confirm with you:
1. Is there a way to visit the annotated documents and change the annotations at all?
2. If I am not satisfy with a model that I trained using 100 documents, and I would like to add 50 more annotated documents to train the model (150 training documents total), will I have to relabel the 150 documents or can I just merge the 50 newly annotated documents with the 100 previously annotated documents and use them as a whole? I am assuming that I will just have to merge the two output.manifest files into one right?

**Comment by dnlen** [comment]
1. You can edit all annotation files for a job using the tool's `--blind1-labeling-job-name` option. This labeling job will iterate through every annotated page in the job, allowing you to edit, add, delete entities (or simply leave them by directly clicking Submit for that page when the annotation file loads). Note that you will have to go through EVERY single annotation file. We have a backlog task for allowing you to only edit individual annotations in a job.
2. Our training API includes an option to include up to [5 manifest files](https://docs.aws.amazon.com/comprehend/latest/dg/API_EntityRecognizerInputDataConfig.html#comprehend-Type-EntityRecognizerInputDataConfig-AugmentedManifests), so you could submit the two jobs' files together. If you have more than 5 labeling jobs, you are correct in that you'd need to merge your output.manifest files until you have <=5. Note: All annotation files in an output.manifest file are required to be in the same S3 location (the same for source files being required to be in the same location), so you will need to edit S3 references in the output.manifest file if you plan to merge output.manifest files.

**Comment by jetsonai11** [comment]
Thank you very much!
