### ISSUE TITLE
make: *** [Makefile:86: ready-and-deploy-guided] Error 2

### ISSUE THREAD

**Issue by harishbattula** [aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools#35]
1. I've created VENV using Virtualenv with python 3.8.10.
2. Installed jq.
3. Have the latest version AWS-cli installed and my AWS credentials for IAM user configured.
4. Downloaded the zip file of this repo and extracted at separate location.
5. Activated new virtual env using path-to-env\Scripts\activate. I can see the version of python 3.8.10.
6. Installed make in PowerShell.
7. While running the single step make command (make ready-and-deploy-guided) as suggested in readme.md file. I'm getting the following error.

## Error Start ##

process_begin: CreateProcess(NULL, sh.exe -c "/usr/bin/which python3.8", ...) failed.
Makefile:32: pipe: No such file or directory
make bootstrap
make[1]: Entering directory 'C:/Users/HBattula/OneDrive - Genzeon Corporation/projects/amazon-comprehend-semi-structured-documents-annotation-tools-main'
process_begin: CreateProcess(NULL, sh.exe -c "/usr/bin/which python3.8", ...) failed.
Makefile:32: pipe: No such file or directory
m pip install aws-sam-cli
process_begin: CreateProcess(NULL, m pip install aws-sam-cli, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: [Makefile:45: bootstrap] Error 2 (ignored)
m pip install pipenv
process_begin: CreateProcess(NULL, m pip install pipenv, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: [Makefile:46: bootstrap] Error 2 (ignored)
m pip install awscli
process_begin: CreateProcess(NULL, m pip install awscli, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: [Makefile:47: bootstrap] Error 2 (ignored)
m pipenv sync -d # Install locked dependencies
process_begin: CreateProcess(NULL, m pipenv sync -d # Install locked dependencies, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: [Makefile:48: bootstrap] Error 2 (ignored)
make[1]: Leaving directory 'C:/Users/HBattula/OneDrive - Genzeon Corporation/projects/amazon-comprehend-semi-structured-documents-annotation-tools-main'
make build
make[1]: Entering directory 'C:/Users/HBattula/OneDrive - Genzeon Corporation/projects/amazon-comprehend-semi-structured-documents-annotation-tools-main'
process_begin: CreateProcess(NULL, sh.exe -c "/usr/bin/which python3.8", ...) failed.
Makefile:32: pipe: No such file or directory
m pipenv requirements > src/requirements.txt
'm' is not recognized as an internal or external command,
operable program or batch file.
make[1]: [Makefile:62: build] Error 1 (ignored)
m pipenv run flake8 src bin
process_begin: CreateProcess(NULL, m pipenv run flake8 src bin, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: [Makefile:63: build] Error 2 (ignored)
m pipenv run pydocstyle src bin
process_begin: CreateProcess(NULL, m pipenv run pydocstyle src bin, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: [Makefile:64: build] Error 2 (ignored)
m pipenv run cfn-lint comprehend-semi-structured-documents-annotation-template.yml
process_begin: CreateProcess(NULL, m pipenv run cfn-lint comprehend-semi-structured-documents-annotation-template.yml, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: [Makefile:65: build] Error 2 (ignored)
sam build --profile default --template comprehend-semi-structured-documents-annotation-template.yml
process_begin: CreateProcess(NULL, sam build --profile default --template comprehend-semi-structured-documents-annotation-template.yml, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [Makefile:66: build] Error 2
make[1]: Leaving directory 'C:/Users/HBattula/OneDrive - Genzeon Corporation/projects/amazon-comprehend-semi-structured-documents-annotation-tools-main'
make: *** [Makefile:86: ready-and-deploy-guided] Error 2

## Error End ##

My ultimate aim is to train Custom Entity Recognition on bunch of pdf's that I've and use model later for inferences.
It'll be great if anyone could help me out on this.

**Comment by dnlen** [comment]
Hello, I saw that you mentioned Powershell. Was this tested using a Windows OS? It is recommended to use a Linux based OS, otherwise you can try AWS Cloud9.

**Comment by harishbattula** [comment]
@dnlen I'm not sure whether it was tested on windows or not, but as you suggested I tried on ubuntu WSL and it is working fine. Thanks..
