### ISSUE TITLE
Will this now support TIFF files as well as PDF

### ISSUE THREAD

**Issue by tomhands1** [aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools#5]
Now that AWS Textract has added support for tiff files analysis as well as PDF's via the AnalyzeDocument method https://aws.amazon.com/about-aws/whats-new/2021/10/amazon-textract-tiff-asynchronous-receipts-invoices/ would this document annotation tool be able to be used for those file types too?

**Comment by dnlen** [comment]
The latest comment has a [separate issue open for it](https://github.com/aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools/issues/10.). Closing this issue.

**Comment by harishbattula** [comment]
> Hi, currently, the image format is not supported by this tool, only PDF format is accepted. But we can take it as the feature request. in the meanwhile, a workaround is to convert image format into PDF format

What file formats it supports for inference??
