### ISSUE TITLE
CloudFormation deployment fails in Sydney region

### ISSUE THREAD

**Issue by jhy** [aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools#7]
Hi,

When trying to `sam deploy` this in the Sydney region, the deployment fails. The S3 bucket name constructed is too long:

```
Fn::Sub: comprehend-semi-structured-documents-${AWS::Region}-${AWS::AccountId}
```

As `$AWS::Region}` is `ap-southeast-2` in Sydney (and my account ID is 12 digits). I worked around this by changing the template.yml to have a shorter prefix.

```
CREATE_FAILED                                           AWS::S3::Bucket                                         SemiStructuredDocumentsS3Bucket                         Bucket name should be between 3 and 63 characters     
                                                                                                                                                                        long    
```

https://github.com/aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools/blob/ba4dade84738e736a7c4e15278d11f80dd10c873/comprehend-semi-structured-documents-annotation-template.yml#L32

**Comment by yinxiaoz-amzn** [comment]
Hi, 
We have merged a fix for this issue.
